name: linux

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
          - '5.38'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          curl -sL https://cpanmin.us/ | perl - -nq --with-develop --installdeps .
      - name: Run Tests
        run: prove -lr t
